version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: stockdb
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/stock-management
      dockerfile: Dockerfile
    container_name: stock-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend/stock-management
      dockerfile: Dockerfile
    container_name: stock-frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/stock-management:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
